---
- name: Configure local environment
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../vars/main.yml
    - ../vars/secrets.yml

  tasks:
    - name: Check for existing inventory
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ DO_API_TOKEN }}"
      register: droplets

    - name: Inspect Droplets
      debug:
        var: droplets

    - name: Count existing droplets
      set_fact:
        droplet_count: "{{ droplets.data | length }}"

    - name: Delete lingering droplets
      debug:
        msg: We should def delete droplets
      when: droplet_count != 0

    - name: Create droplet
      debug:
        msg: Ok make it now with SSH keys setup
