---
- name: Configure local environment
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../vars/main.yml
    - ../vars/secrets.yml

  tasks:
    - name: Check for existing inventory
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ DO_API_TOKEN }}"
      register: droplets

    - name: Inspect Droplets
      debug:
        var: droplets

    - name: Count existing droplets
      set_fact:
        droplet_count: "{{ droplets.data | length }}"

    - name: Delete lingering droplets
      community.digitalocean.digital_ocean_droplet:
        state: absent
        oauth_token: "{{ DO_API_TOKEN }}"
        id: "{{ item.id }}"
      loop: "{{ droplets.data }}"
      when: droplet_count != "0"

    - name: Create SSH key
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ DO_API_TOKEN }}"
        name: "Ansible Key"
        ssh_pub_key: "{{ SSH_PUBLIC_KEY }}"
        state: present
      register: public_key

    - name: Inspect SSH key
      debug:
        var: public_key

#     - name: Create automated builder VPS
#       community.digitalocean.digital_ocean_droplet:
#         state: present
#         oauth_token: "{{ DO_API_TOKEN }}"
#         name: automated_builder_vps
#         size: s-4vcpu-8gb
#         region: nyc3
#         image: debian-11-x64
#         wait_timeout: 500
#         ssh_keys: "{{ SSH_KEY }}"
#         project: "Automated Builder"
#       register: automated_builder_vps
