---
- name: Generate DigitalOcean inventory
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ../vars/main.yml
    - ../vars/secrets.yml

  tasks:
    - name: Create SSH key
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ DO_API_TOKEN }}"
        name: "Ansible Key"
        ssh_pub_key: "{{ SSH_PUBLIC_KEY }}"
        state: present
      register: public_key

    - name: Create automated builder VPS
      community.digitalocean.digital_ocean_droplet:
        state: present
        oauth_token: "{{ DO_API_TOKEN }}"
        name: automated-builder-vps
        size: s-8vcpu-16gb
        region: nyc3
        image: debian-11-x64
        wait_timeout: 500
        ssh_keys: ["{{ public_key.data.ssh_key.id }}"]
        project: "Automated Builder"
      register: automated_builder_vps
