---
- name: Build VMs
  hosts: vps_runner
  gather_facts: true
  vars_files:
    - ../vars/secrets.yml
    - ../vars/main.yml

- name: Start new VirtualBox VMs
  block:
    - name: Start new vbox VMs
      include_tasks: start_new_vbox_vms.yml
  environment:
    DISPLAY: "localhost:1"

- name: Create run_wats script
  template:
    src: ../templates/run_wats.sh
    dest: /home/ansible/run_wats.sh

- name: Copy run_wats script to guest
  shell: 'VBoxManage guestcontrol Whonix-Workstation-XFCE copyto /home/ansible/run_wats.sh /home/user/ --username user --password changeme'

- name: Change script mode for execution
  shell: 'VBoxManage guestcontrol Whonix-Workstation-XFCE run --exe "/bin/chmod" --username user --password changeme -- chmod 777 /home/user/run_wats.sh'

- name: Run test suite
  shell: 'VBoxManage guestcontrol Whonix-Workstation-XFCE run --exe /home/user/run_wats.sh --username user --password changeme'
