---
- name: Start VNC display
  shell: "vncserver"

- name: Add xhost
  shell: "xhost +"

- name: Start gateway VM
  shell: "VBoxManage startvm Whonix-Gateway-XFCE"

- name: Start workstation VM
  shell: "VBoxManage startvm Whonix-Workstation-XFCE"

- name: Wait for VMs to boot and connect to tor
  pause:
    minutes: 2
