---
- name: Install build_vms_from_commit script
  template:
    src: ../templates/build_vms_from_commit.sh
    dest: /home/ansible/build_vms_from_commit.sh
    mode: 0744

- name: Run build_vms_from_commit scripts
  shell: "DEBUG_BUILD={{ DEBUG_BUILD }} /home/ansible/build_vms_from_commit.sh"
