---
- name: Run automated_builder
  hosts: vps_runner
  gather_facts: false
  vars_files:
    - ./roles/common/vars/main.yml
    - ./roles/common/vars/secrets.yml

  tasks:
    - name: Include common role
      include_role:
        name: common
