---
- name: Register running VMs
  shell: "VBoxManage list runningvms"
  register: running_vms

- name: Shutdown gateway VM
  shell: "VBoxManage controlvm Whonix-Gateway-XFCE acpipowerbutton"
  when: "'Whonix-Gateway-XFCE' in running_vms.stdout"

- name: Shutdown workstation VM
  shell: "VBoxManage controlvm Whonix-Workstation-XFCE acpipowerbutton"
  when: "'Whonix-Workstation-XFCE' in running_vms.stdout"

- name: Pause for machine shutdown
  pause:
    minutes: 1
  when: "'Whonix-Workstation-XFCE' or 'Whonix-Workstation-XFCE' in running_vms.stdout"

- name: Register existing VMs
  shell: "VBoxManage list vms"
  register: existing_vms

- name: Delete gateway VM
  shell: "VBoxManage unregistervm Whonix-Gateway-XFCE --delete"
  when: "'Whonix-Gateway-XFCE' in existing_vms.stdout"

- name: Delete workstation VM
  shell: "VBoxManage unregistervm Whonix-Workstation-XFCE --delete"
  when: "'Whonix-Workstation-XFCE' in existing_vms.stdout"
