---
- name: Destroy any lingering droplets
  delegate_to: 127.0.0.1
  block:
    - name: Check for existing inventory
      community.digitalocean.digital_ocean_droplet_info:
        oauth_token: "{{ DO_API_TOKEN }}"
      register: droplets

    - name: Count existing droplets
      set_fact:
        droplet_count: "{{ droplets.data | length }}"

    - name: Delete lingering droplets
      community.digitalocean.digital_ocean_droplet:
        state: absent
        oauth_token: "{{ DO_API_TOKEN }}"
        id: "{{ item.id }}"
      loop: "{{ droplets.data }}"
      when: droplet_count != "0"
