---
- name: Create install_verified_source script
  template:
    src: ../templates/install_verified_source.sh
    dest: /home/ansible/install_verified_source.sh
    mode: 0744

- name: Run install_verified_source script for tag
  shell: "/home/ansible/install_verified_source.sh {{ GIT_REPO }} {{ REF_NAME }} {{ REF_NAME }} > /home/ansible/install_verified_source.log 2>&1"
  when: REF_TYPE == 'tag'

- name: Run install_verified_source script for commit
  shell: "/home/ansible/install_verified_source.sh {{ GIT_REPO }} {{ REF_NAME }} > /home/ansible/install_verified_source.log 2>&1"
  when: REF_TYPE != 'tag'
