---
- name: Install dependencies
  become: true
  block:
    - name: Install apt packages
      apt:
        pkg:
          - git
          - time
          - curl
          - lsof
          - apt-cacher-ng
          - lsb-release
          - fakeroot
          - dpkg-dev
          - fasttrack-archive-keyring
          - dnsutils
        update_cache: true

    - name: Upgrade apt packages
      apt:
        upgrade: full
