---
- name: Delete existing inventory
  include_tasks: delete_inventory.yml

- name: Generate inventory
  include_tasks: generate_inventory.yml

- name: Configure local environment
  include_tasks: configure_local_environment.yml

- name: Bootstrap VPS
  include_tasks: bootstrap_vps.yml

- name: Gathering facts
  setup:

- name: Install dependencies
  include_tasks: install_dependencies.yml

- name: Install source and submodules
  include_tasks: install_source.yml

- name: Clean existing VirtualBox VMs
  include_tasks: clean_existing_vbox_vms.yml

- name: Create VMs from tag
  include_tasks: create_vms_from_tag.yml
  when: REF_TYPE == 'tag'

- name: Create VMs from commit
  include_tasks: create_vms_from_commit.yml
  when: REF_TYPE != 'tag'

- name: Start new VirtualBox VMs
  include_tasks: start_new_vbox_vms.yml
