name: Build VMs
on: push

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      REPO_URL: ${{ github.repository }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    # TODO: Check for existing VPS, create new Virtual Private Server(s) for tag push or commit push
    # - name: Manage DigitalOcean assets
    #   run: |
    #     ./automated_builder/scripts/create_vps.sh $ANSIBLE_VAULT_PASSWORD

    # TODO: create seperate roles for tag push and commit push
    - name: Run automated builder
      run: |
        ./automated_builder/scripts/run_automated_builder.sh $ANSIBLE_VAULT_PASSWORD

    - name: Run automated test suite
      run: |
        ./automated_builder/scripts/run_automated_test_suite.sh $ANSIBLE_VAULT_PASSWORD
      # if: startsWith(github.ref, 'refs/tags/v')

    # TODO: Handle aggregation of logs from multiple VMs when commit push occurs. Rename logs and create more clear folder structures
    - name: Gather artifacts
      if: always()
      run: |
        ./automated_builder/scripts/handle_artifacts.sh $ANSIBLE_VAULT_PASSWORD

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: logs
        path: ./automated_builder/logs/

    # TODO: Teardown VPS job
